import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/organisms/Navbar/Navbar";
import Footer from "@/components/organisms/Footer/Footer";
import AuthModals from "@/components/molecules/AuthModals/AuthModals";
import Sidebar from "@/components/organisms/Sidebar/Sidebar";
import QueryProvider from "@/providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full w-full flex flex-col justify-between bg-[#F5F5F5]!">
         <QueryProvider>
              <Navbar/>
              {children}
              <Footer/>
              <AuthModals />
              <Sidebar />
         </QueryProvider>
      </body>
    </html>
  );
}
